package me.kev.sva.chat.message;

import me.kev.sva.ServerAssistantPlugin;

/** Internal trusted context generated by the server/plugin, never by players. */
public class SystemContextMessage extends ChatMessage {
  public final String header;

  public SystemContextMessage(ServerAssistantPlugin plugin, String header, String content) {
    super(plugin, content);
    this.header = header == null ? "[SERVER CONTEXT] " : header;
  }
}
